# Generated by Django 5.2.2 on 2026-02-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0007_add_obra'),
        ('recursos', '0012_add_dolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('instancia', models.CharField(max_length=80)),
                ('fecha_dolar', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='general.company')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='recursos.lote')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='general.obra')),
                ('tipo_dolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='general.tipodolar')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['obra__nombre', '-fecha', 'instancia'],
                'unique_together': {('company', 'obra', 'instancia')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.presupuesto')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_items', to='recursos.tarea')),
            ],
            options={
                'verbose_name': 'Item de Presupuesto',
                'verbose_name_plural': 'Items de Presupuesto',
                'unique_together': {('presupuesto', 'tarea')},
            },
        ),
    ]
