# Generated by Django 5.2.2 on 2026-02-12 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='categoriamaterial',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subrubro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='categoriamaterial',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subrubro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoriamaterial',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_material', to='general.company'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='general.company'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='general.company'),
        ),
        migrations.AddField(
            model_name='subrubro',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='general.company'),
        ),
        migrations.AddField(
            model_name='tipomaterial',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_material', to='general.company'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='general.company'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriamaterial',
            unique_together={('company', 'tipo', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('company', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='rubro',
            unique_together={('company', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='subrubro',
            unique_together={('company', 'rubro', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='tipomaterial',
            unique_together={('company', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='unidad',
            unique_together={('company', 'nombre')},
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='general.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership empresa',
                'verbose_name_plural': 'Memberships empresa',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
