# Generated by Django 5.2.2 on 2026-02-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_refequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_dolar', to='general.company')),
            ],
            options={
                'verbose_name': 'Tipo de Dólar',
                'verbose_name_plural': 'Tipos de Dólar',
                'ordering': ['nombre'],
                'unique_together': {('company', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CotizacionDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_dolar', to='general.company')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='general.tipodolar')),
            ],
            options={
                'verbose_name': 'Cotización Dólar',
                'verbose_name_plural': 'Cotizaciones Dólar',
                'ordering': ['-fecha', 'tipo__nombre'],
                'unique_together': {('company', 'fecha', 'tipo')},
            },
        ),
    ]
