# Generated by Django 5.2.2 on 2026-02-12 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_add_dolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('pisos', models.CharField(blank=True, help_text='Ej: PB + 2 pisos', max_length=100)),
                ('m2_construibles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('m2_vendibles', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_terreno', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='general.company')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['nombre'],
                'unique_together': {('company', 'nombre')},
            },
        ),
    ]
