# Generated by Django 5.2.2 on 2026-02-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_set_default_company"),
        ("recursos", "0002_hojaprecios_hojapreciomaterial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manodeobra',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hojaprecios',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hojas_precios', to='general.company'),
        ),
        migrations.AddField(
            model_name='manodeobra',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mano_de_obra', to='general.company'),
        ),
        migrations.AddField(
            model_name='material',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='general.company'),
        ),
        migrations.AddField(
            model_name='subcontrato',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontratos', to='general.company'),
        ),
        migrations.AlterField(
            model_name='hojaprecios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subcontrato',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='hojaprecios',
            unique_together={('company', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='manodeobra',
            unique_together={('company', 'descripcion_puesto', 'equipo')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('company', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='subcontrato',
            unique_together={('company', 'descripcion')},
        ),
    ]
