# Generated by Django 5.2.2 on 2026-02-12 18:19

import django.db.models.deletion
from django.db import migrations, models


def migrar_equipos(apps, schema_editor):
    """Crear Equipos desde los valores existentes y vincular ManoDeObra."""
    ManoDeObra = apps.get_model("recursos", "ManoDeObra")
    Equipo = apps.get_model("general", "Equipo")

    for md in ManoDeObra.objects.all():
        equipo_nombre = md.equipo_old
        company = md.company
        equipo, _ = Equipo.objects.get_or_create(
            company=company,
            nombre=equipo_nombre,
            defaults={"nombre": equipo_nombre},
        )
        md.equipo_new = equipo
        md.save()


def reverse_migrar(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_equipo"),
        ("recursos", "0004_set_default_company"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="manodeobra",
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name="manodeobra",
            old_name="equipo",
            new_name="equipo_old",
        ),
        migrations.AddField(
            model_name="manodeobra",
            name="equipo_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mano_de_obra_temp",
                to="general.equipo",
            ),
        ),
        migrations.RunPython(migrar_equipos, reverse_migrar),
        migrations.RemoveField(
            model_name="manodeobra",
            name="equipo_old",
        ),
        migrations.RenameField(
            model_name="manodeobra",
            old_name="equipo_new",
            new_name="equipo",
        ),
        migrations.AlterField(
            model_name="manodeobra",
            name="equipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mano_de_obra",
                to="general.equipo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="manodeobra",
            unique_together={("company", "descripcion_puesto", "equipo")},
        ),
    ]
