# Generated by Django 5.2.3 on 2026-02-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_subcontrato_hojas_reestructura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontrato',
            options={'ordering': ['rubro__nombre', 'subrubro__nombre', 'tarea'], 'verbose_name': 'Subcontrato', 'verbose_name_plural': 'Subcontratos'},
        ),
    ]
