# Generated by Django 5.2.2 on 2026-02-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_refequipo'),
        ('recursos', '0008_manodeobra_hojas_reestructura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manodeobra',
            options={'ordering': ['rubro__nombre', 'subrubro__nombre', 'tarea'], 'verbose_name': 'Mano de Obra', 'verbose_name_plural': 'Mano de Obra'},
        ),
        migrations.CreateModel(
            name='Mezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mezclas', to='general.company')),
                ('hoja', models.ForeignKey(blank=True, help_text='Hoja de materiales para precios. Si vacío, usa precios actuales.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mezclas', to='recursos.hojaprecios')),
                ('unidad_de_mezcla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mezclas', to='general.unidad')),
            ],
            options={
                'verbose_name': 'Mezcla',
                'verbose_name_plural': 'Mezclas',
                'ordering': ['nombre'],
                'unique_together': {('company', 'nombre', 'hoja')},
            },
        ),
        migrations.CreateModel(
            name='MezclaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Cantidad en unidad de venta del material (ej: bolsas, kg).', max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mezclas', to='recursos.material')),
                ('mezcla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recursos.mezcla')),
            ],
            options={
                'verbose_name': 'Material en Mezcla',
                'verbose_name_plural': 'Materiales en Mezcla',
                'ordering': ['material__nombre'],
                'unique_together': {('mezcla', 'material')},
            },
        ),
    ]
