# Generated by Django 5.2.2 on 2026-02-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_refequipo'),
        ('recursos', '0009_mezcla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='general.company')),
                ('hoja_mano_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='recursos.hojapreciosmanodeobra')),
                ('hoja_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='recursos.hojaprecios')),
                ('hoja_subcontratos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='recursos.hojapreciossubcontrato')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-creado_en'],
                'unique_together': {('company', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='general.company')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='recursos.lote')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='general.rubro')),
                ('subrubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='general.subrubro')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Maestro Tareas',
                'ordering': ['rubro__nombre', 'subrubro__nombre', 'nombre'],
                'unique_together': {('company', 'lote', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TareaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('mano_de_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarea_recursos', to='recursos.manodeobra')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarea_recursos', to='recursos.material')),
                ('mezcla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarea_recursos', to='recursos.mezcla')),
                ('subcontrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarea_recursos', to='recursos.subcontrato')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='recursos.tarea')),
            ],
            options={
                'verbose_name': 'Recurso en Tarea',
                'verbose_name_plural': 'Recursos en Tarea',
            },
        ),
    ]
