# Generated by Django 5.2.2 on 2026-02-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_refequipo'),
        ('recursos', '0010_lote_maestro_tareas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('company', 'nombre', 'proveedor')},
        ),
    ]
