# Generated by Django 5.2.2 on 2026-02-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_add_dolar'),
        ('recursos', '0011_material_proveedor_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='fecha_dolar',
            field=models.DateField(blank=True, help_text='Fecha de cotización para convertir ARS a USD.', null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_dolar',
            field=models.ForeignKey(blank=True, help_text='Tipo de dólar para ver precios en USD.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='general.tipodolar'),
        ),
    ]
